### ISSUE TITLE
Flaky test test_reorged_cancel

### ISSUE THREAD

**Issue by danielabrozzoni** [revault/revaultd#236] opened 2021-07-20 12:37 UTC
What happens in `test_reorged_cancel` is that sometimes some participants see the transaction as `spent` instead of `canceled`.

https://github.com/revault/revaultd/blob/1261b190be9f37c66369b72f703e50a393277247/tests/test_misc.py#L1415-L1420

The problem is in the function `unvault_spender`, which fails to recognize the cancel as a cancel, returns it as if it was a spend instead.

https://github.com/revault/revaultd/blob/1261b190be9f37c66369b72f703e50a393277247/src/daemon/bitcoind/poller.rs#L891-L930

This happens because, for some reason, `is_current` with the `cancel_txid` returns `Err(Server(Rpc(RpcError { code: -5, message: "Invalid or non-wallet transaction id", data: None })))` here:
https://github.com/revault/revaultd/blob/1261b190be9f37c66369b72f703e50a393277247/src/daemon/bitcoind/poller.rs#L908-L911

A couple of lines below, we retrieve the spender of the unvault (which is still the cancel_txid) assuming it's a spend, and `is_current` returns `true`:
https://github.com/revault/revaultd/blob/1261b190be9f37c66369b72f703e50a393277247/src/daemon/bitcoind/poller.rs#L921-L927
So we return "yo, the unvault has been spent by the Spend tx *cancel_txid*", we mark the vault as spent, and the test fails.

I think `is_current` is behaving like that because it takes some time for the node to re-align itself after a big reorg.

We could solve this problem by fetching the spender of the unvault `bitcoind.get_spender_txid(&unvault_outpoint, &previous_tip.hash)?` and then compare it to the `cancel_txid`, `unemer_txid`, or otherwise return it as a spend.
What do you think?

**Comment by darosior** [comment] 2021-07-20 13:19
Good catch.

I agree. I think there is a bug in the `unvault_spender` logic: it shouldn't mark it as a Spend if the spending tx is actually a presigned tx (we can check that) because it would otherwise stick! https://github.com/revault/revaultd/blob/5dfbf0618f504a12a122202cac7c8668fd12a51f/src/daemon/bitcoind/poller.rs#L920-L927

While thinking about this, i think there are different possibilities to make these edge cases less likely to be triggered, all hacks:
1. Wait longer when polling the tip, we can afford it since reorgs are expected to be really rare under normal conditions. https://github.com/revault/revaultd/blob/5dfbf0618f504a12a122202cac7c8668fd12a51f/src/daemon/bitcoind/poller.rs#L597-L605 Of course this is still a race, but will be caught at the next poll.
2. Have a better detection of `bitcoind` continuing to process blocks while we are rescaning. Our current mechanism is pretty useless and we could at least check the tip didn't change https://github.com/revault/revaultd/blob/5dfbf0618f504a12a122202cac7c8668fd12a51f/src/daemon/bitcoind/poller.rs#L636-L639 Although this is not a big issue as such as we would detect the reorg at the next poll.
3. Force re-broadcast of pre-signed transactions. If we notice a previously-confirmed transaction went unconfirmed, we `sendrawtransaction` it to force its inclusion in the mempool. Actually we did this before but i removed it as i figured it wasn't really useful and `bitcoind` would just do the job.

**Comment by danielabrozzoni** [comment] 2021-07-21 12:46
I've added a commit in #237 that fixes the trouble, but doesn't implement your suggestions. We can leave this issue open, so we can work on the suggestions later

**Comment by darosior** [comment] 2021-07-21 12:57
No they aren't really suggestions, i think it's better to close this now and know where to find it in case we ever need it :)

**Closed** 2021-07-22 07:34 UTC
Labels: bug
